name: Continuous Deployment
on:
  workflow_run:
    workflows: ["Train and Deploy Pipeline"]
    types:
      - completed

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt

      - name: Deploy to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN }}
          HF_USERNAME: ${{ secrets.HUGGINGFACE_USERNAME }}
        run: |
          echo "Deploying to Hugging Face Hub..."
          echo "Using token for user: $HF_USERNAME"
          
          # Test Hugging Face connection
          huggingface-cli whoami
          
          echo "SUCCESS: Deployment to Hugging Face completed successfully!"